// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.newPostsHandle = Meteor.subscribeWithPagination('newPosts', 5);

  root.bestPostsHandle = Meteor.subscribeWithPagination('bestPosts', 5);

  Deps.autorun(function() {
    Meteor.subscribe('specificPost', Session.get('currentPostId'));
    return Meteor.subscribe('comments', Session.get('currentPostId'));
  });

  Meteor.subscribe('notifications');

  Meteor.subscribe('postsFiles');

}).call(this);
